#!/bin/sh

if [ -d ../.git -o -d ../.svn ]; then
    if [ -d ../.git ]; then
	prefix="git "
    fi
    revision=$($prefix svn info | grep Revision: | egrep -o '[0-9]+')
    revision=$(printf '%04d' $revision)

    echo "Generating images for revision $revision"
fi

# A dir specific for outputs
mkdir -p outputs
    
for f in "$@"; do
    echo "Running $f";

    if [ "$revision" ]; then
	output=outputs/${f%%.sh}-$revision
    else
	output=outputs/${f%%.sh}
    fi
    basepdf=${f%%.sh}

    export CT_ADD="--name ${basepdf}-%03d"
    NOXPDF=1 sh $f
    if [ -r ${basepdf}-000.pdf ]; then
	echo "There are outputs"
	echo " -> producing montage outputs"
    
	if [ -z $BIG ]; then
	    geometry=340x340+4+4
	    density=150
	else
	    geometry=500x500+4+4
	    density=250
	fi
	montage -label %f -frame 5 -background '#336699' \
	    -geometry $geometry -density $density ${basepdf}-*.pdf ${output}.png
	if [ -z $KEEP ]; then
	    echo " -> removing PDF files"
	    rm -f ${basepdf}-*.pdf
	fi
	display ${output}.png &
    fi
done
