#! /bin/sh

# A small script file to help release a new version of ctioga2

version="$1"

rep=svn+ssh://rubyforge.org/var/svn/ctioga2/

base=ctioga2-$version
tg=$rep/releases/$base

echo "Looking for relase $version"
if svn ls $tg 2>/dev/null >/dev/null; then
    echo "Release number $version already exists, aborting"
    exit 1
fi

echo "Tagging relese $version"
svn copy -m "[ctioga2] tagging release $version" "$rep/trunk/ctioga2" "$tg"

tmpdir=$(mktemp -d)
curdir=`pwd`
cd $tmpdir
echo "Exporting tagged version"
svn export "$tg" "$base"
tar cvjf "$base".tar.bz2 "$base"
cd "$base"
gem build ctioga2.gemspec
cd $curdir
cp -v $tmpdir/"$base".tar.bz2 $tmpdir/"$base"/"$base".gem .